---
#
# Default arguments to use if absent from command-line.
#
defaults:
  keyStore:
    # Keystore password -k default
    password: changeit

    # Parameter -a default
    private-key-alias: javalaboratories-org

    # Parameter -v default
    file: keys-vault.jks
...